### ISSUE TITLE
Responses don't return all 'set-cookie' headers

### ISSUE THREAD

**Issue by bradryannelson** [heydryft/tlsclient.js#1]
it's possible for there to be multiple headers with the same key ('set-cookie' for example). If there are multiple, it will only return 1. 

ex: 
    'Set-Cookie': 'cookieA=value; path=/; secure; HttpOnly; SameSite=None',
    'Set-Cookie': 'cookieB=value; path=/; secure; HttpOnly; SameSite=None',
    'Set-Cookie': 'cookieC=value; path=/; secure; HttpOnly; SameSite=None',

 will only return 
    'Set-Cookie': 'cookieA=value; path=/; secure; HttpOnly; SameSite=None',

**Comment by heydryft** [comment]
I think this was fixed with the latest merge, can you check?

**Comment by preaverage** [comment]
hey, same issue still only returning first cookie. I have also tried using tough-cookie with this using the axios cookie jar wrapper and it doesnt see the set-cookie header.

**Comment by Maxou44** [comment]
Same issue on my side, only the first set-cookie header is available
